#!/bin/sh
set -e

FILTER_VARS='$VOD_SEGMENT_DURATION $VOD_METADATA_CACHE_SIZE $VOD_RESPONSE_CACHE_SIZE $VOD_MAPPING_CACHE_SIZE $API_UPSTREAM_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION $AWS_ENDPOINT $AWS_BUCKET $VOD_TOKEN_SECRET $SECURE_TOKEN_EXPIRES_TIME $SECURE_TOKEN_QUERY_EXPIRES_TIME'
envsubst "$FILTER_VARS" < /usr/local/nginx/conf/nginx.conf.template > /usr/local/nginx/conf/nginx.conf

exec /usr/local/nginx/sbin/nginx -g "daemon off;"
