#!/bin/bash
set -e

FILTER_VARS='$VOD_SEGMENT_DURATION $VOD_METADATA_CACHE_SIZE $VOD_RESPONSE_CACHE_SIZE $VOD_MAPPING_CACHE_SIZE $API_UPSTREAM_HOST $AWS_ACCESS_KEY $AWS_SECRET_KEY $AWS_REGION $S3_PROXY_URL $S3_BUCKET_NAME $VOD_TOKEN_SECRET $SECURE_TOKEN_EXPIRES_TIME $SECURE_TOKEN_QUERY_EXPIRES_TIME'
envsubst "$FILTER_VARS" < /usr/local/nginx/conf/nginx.conf.template > /usr/local/nginx/conf/nginx.conf

exec /usr/local/nginx/sbin/nginx -g "daemon off;"
