<?php

return [
    'codecs' => [
        // ========== VIDEO CODECS ==========
        [
            'codec' => 'libx264',
            'type' => 'video',
            'label' => 'H.264 (AVC)',
            'description' => 'High compatibility. Works everywhere.',
            'container' => 'mp4',
            'protocols' => ['hls', 'dash'],
        ],
        [
            'codec' => 'libx265',
            'type' => 'video',
            'label' => 'H.265 (HEVC)',
            'description' => 'Better compression than H.264. Good for 4K.',
            'container' => 'mp4',
            'protocols' => ['hls', 'dash'],
        ],
        [
            'codec' => 'libsvtav1',
            'type' => 'video',
            'label' => 'AV1 (SVT-AV1)',
            'description' => 'Best compression, royalty-free. Slow encoding.',
            'container' => 'mp4',
            'protocols' => ['hls', 'dash'],
        ],
        [
            'codec' => 'libvpx',
            'type' => 'video',
            'label' => 'VP8',
            'description' => 'Legacy WebM codec. Use VP9 instead for new projects.',
            'container' => 'webm',
            'protocols' => ['dash'],
        ],
        [
            'codec' => 'libvpx-vp9',
            'type' => 'video',
            'label' => 'VP9',
            'description' => 'Good compression, royalty-free. Widely supported in browsers.',
            'container' => 'webm',
            'protocols' => ['dash'],
        ],

        // ========== AUDIO CODECS ==========
        [
            'codec' => 'aac',
            'type' => 'audio',
            'label' => 'AAC',
            'description' => 'Standard audio codec with good compatibility.',
            'container' => 'mp4',
            'available_for' => ['libx264', 'libx265', 'libsvtav1'],
        ],
        [
            'codec' => 'libfdk_aac',
            'type' => 'audio',
            'label' => 'FDK-AAC',
            'description' => 'The best AAC encoder available.',
            'container' => 'mp4',
            'available_for' => ['libx264', 'libx265', 'libsvtav1'],
        ],
        [
            'codec' => 'libvorbis',
            'type' => 'audio',
            'label' => 'Vorbis',
            'description' => 'Open-source codec for WebM containers.',
            'container' => 'webm',
            'available_for' => ['libvpx', 'libvpx-vp9'],
        ],
        [
            'codec' => 'libopus',
            'type' => 'audio',
            'label' => 'Opus',
            'description' => 'Best open-source audio codec. Low latency, high quality.',
            'container' => 'webm',
            'available_for' => ['libvpx-vp9', 'libsvtav1'],
        ],
    ],

    'parameters' => [
        // ==========================================
        // VIDEO PARAMETERS
        // ==========================================

        'resolution' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Resolution',
            'options' => ['360', '480', '720', '1080', '1440', '2160'],
            'rules' => ['required', 'in:360,480,720,1080,1440,2160'],
            'template' => '-vf scale=-2:%s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],

        // --- H.264 specific ---
        'crf' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CRF',
            'min' => 0,
            'max' => 51,
            'help' => 'Lower is better quality. 23 is the default for H.264.',
            'rules' => ['integer', 'min:0', 'max:51'],
            'template' => '-crf %s',
            'available_for' => ['libx264', 'libx265'],
        ],
        'preset' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Preset',
            'options' => ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower', 'veryslow'],
            'rules' => ['in:ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow'],
            'template' => '-preset %s',
            'available_for' => ['libx264', 'libx265'],
        ],
        'video_profile' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Profile',
            'options' => ['baseline', 'main', 'high'],
            'rules' => ['in:baseline,main,high'],
            'template' => '-profile:v %s',
            'available_for' => ['libx264'],
        ],
        'tune' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Tune',
            'options' => ['film', 'animation', 'grain', 'stillimage', 'fastdecode', 'zerolatency'],
            'help' => 'Adjust the encoder according to the type of content.',
            'rules' => ['in:film,animation,grain,stillimage,fastdecode,zerolatency'],
            'template' => '-tune %s',
            'available_for' => ['libx264'],
        ],
        'level' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Level',
            'options' => ['3.0', '3.1', '4.0', '4.1', '4.2', '5.1', '5.2'],
            'help' => 'Defines technical restrictions. 4.1 is the standard for Blu-ray/Web.',
            'rules' => ['in:3.0,3.1,4.0,4.1,4.2,5.1,5.2'],
            'template' => '-level %s',
            'available_for' => ['libx264'],
        ],
        'maxrate' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'Maxrate',
            'placeholder' => 'e.g. 5000k',
            'help' => 'Useful for streaming (VBV). Prevents data spikes that cause buffering.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-maxrate %s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],
        'bufsize' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'Bufsize',
            'placeholder' => 'e.g. 10000k',
            'help' => 'Used together with Maxrate to control the bitrate.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-bufsize %s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],
        'pixel_format' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Pixel format',
            'options' => ['yuv420p', 'yuv420p10le', 'yuv422p', 'yuv444p'],
            'help' => 'yuv420p is compatible with all browsers and devices. 10le for HDR/10-bit.',
            'rules' => ['in:yuv420p,yuv420p10le,yuv422p,yuv444p'],
            'template' => '-pix_fmt %s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],
        'faststart' => [
            'type' => 'video',
            'input_type' => 'boolean',
            'label' => 'Faststart',
            'help' => 'Moves metadata to the beginning so the video starts playing sooner.',
            'rules' => ['boolean'],
            'template' => '-movflags +faststart',
            'available_for' => ['libx264', 'libx265', 'libsvtav1'],
        ],
        'constant_bitrate' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'Target Bitrate',
            'placeholder' => 'e.g. 2500k',
            'help' => 'Target bitrate. For CRF-based codecs, this sets a bitrate ceiling.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-b:v %s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],
        'gop_size' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'GOP Size (Keyframes)',
            'help' => 'Distance between keyframes. For streaming use 2x framerate (e.g. 60 for 30fps).',
            'rules' => ['nullable', 'integer', 'min:1'],
            'template' => '-g %s',
            'available_for' => ['libx264', 'libx265', 'libsvtav1', 'libvpx', 'libvpx-vp9'],
        ],

        // --- H.265 specific ---
        'x265_profile' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'HEVC Profile',
            'options' => ['main', 'main10', 'main444-8', 'main444-10'],
            'rules' => ['in:main,main10,main444-8,main444-10'],
            'template' => '-profile:v %s',
            'available_for' => ['libx265'],
        ],
        'x265_tune' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'HEVC Tune',
            'options' => ['grain', 'animation', 'fastdecode', 'zerolatency'],
            'rules' => ['in:grain,animation,fastdecode,zerolatency'],
            'template' => '-tune %s',
            'available_for' => ['libx265'],
        ],
        'hevc_tag' => [
            'type' => 'video',
            'input_type' => 'boolean',
            'label' => 'Apple HVC1 Tag',
            'help' => 'Required for Apple device compatibility with HEVC.',
            'rules' => ['boolean'],
            'template' => '-tag:v hvc1',
            'available_for' => ['libx265'],
        ],

        // --- AV1 (SVT-AV1) specific ---
        'svtav1_crf' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CRF',
            'min' => 0,
            'max' => 63,
            'help' => 'Lower is better quality. 30 is a good default for AV1.',
            'rules' => ['integer', 'min:0', 'max:63'],
            'template' => '-crf %s',
            'available_for' => ['libsvtav1'],
        ],
        'svtav1_preset' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'Preset',
            'min' => 0,
            'max' => 13,
            'help' => '0 = slowest/best quality, 13 = fastest. 6-8 is a good balance.',
            'rules' => ['integer', 'min:0', 'max:13'],
            'template' => '-preset %s',
            'available_for' => ['libsvtav1'],
        ],

        // --- VP8 specific ---
        'vp8_crf' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CRF',
            'min' => 4,
            'max' => 63,
            'help' => 'Lower is better quality. 10 is a good default for VP8.',
            'rules' => ['integer', 'min:4', 'max:63'],
            'template' => '-crf %s',
            'available_for' => ['libvpx'],
        ],
        'vp8_quality' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Quality mode',
            'options' => ['good', 'best', 'realtime'],
            'help' => '"good" balances speed and quality. "best" is slowest.',
            'rules' => ['in:good,best,realtime'],
            'template' => '-quality %s',
            'available_for' => ['libvpx'],
        ],
        'vp8_cpu_used' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CPU Used',
            'min' => 0,
            'max' => 5,
            'help' => 'Higher = faster encoding but lower quality.',
            'rules' => ['integer', 'min:0', 'max:5'],
            'template' => '-cpu-used %s',
            'available_for' => ['libvpx'],
        ],

        // --- VP9 specific ---
        'vp9_crf' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CRF',
            'min' => 0,
            'max' => 63,
            'help' => 'Lower is better quality. 31 is a good default for VP9.',
            'rules' => ['integer', 'min:0', 'max:63'],
            'template' => '-crf %s',
            'available_for' => ['libvpx-vp9'],
        ],
        'vp9_quality' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Quality mode',
            'options' => ['good', 'best', 'realtime'],
            'rules' => ['in:good,best,realtime'],
            'template' => '-quality %s',
            'available_for' => ['libvpx-vp9'],
        ],
        'vp9_cpu_used' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CPU Used',
            'min' => 0,
            'max' => 8,
            'help' => 'Higher = faster encoding but lower quality.',
            'rules' => ['integer', 'min:0', 'max:8'],
            'template' => '-cpu-used %s',
            'available_for' => ['libvpx-vp9'],
        ],
        'vp9_row_mt' => [
            'type' => 'video',
            'input_type' => 'boolean',
            'label' => 'Row Multi-threading',
            'help' => 'Enables row-based multi-threading for faster encoding.',
            'rules' => ['boolean'],
            'template' => '-row-mt 1',
            'available_for' => ['libvpx-vp9'],
        ],
        'vp9_tile_columns' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Tile Columns',
            'options' => ['0', '1', '2', '3', '4'],
            'help' => 'Splits frame into columns for parallel encoding. 2-4 for 1080p+.',
            'rules' => ['in:0,1,2,3,4'],
            'template' => '-tile-columns %s',
            'available_for' => ['libvpx-vp9'],
        ],

        // ==========================================
        // AUDIO PARAMETERS
        // ==========================================

        'audio_bitrate' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Audio Bitrate',
            'options' => ['64k', '96k', '128k', '160k', '192k', '256k', '320k', '448k', '640k'],
            'rules' => ['in:64k,96k,128k,160k,192k,256k,320k,448k,640k'],
            'template' => '-b:a %s',
            'available_for' => ['aac', 'libfdk_aac', 'libopus'],
        ],
        'sample_rate' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Sample Rate',
            'options' => ['22050', '32000', '44100', '48000'],
            'help' => '44100Hz is the CD standard; 48000Hz is used in professional video.',
            'rules' => ['in:22050,32000,44100,48000'],
            'template' => '-ar %s',
            'available_for' => ['aac', 'libfdk_aac', 'libvorbis', 'libopus'],
        ],
        'channels' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Channels',
            'options' => ['1', '2', '6'],
            'help' => '1 = mono, 2 = stereo, 6 = 5.1 surround.',
            'rules' => ['in:1,2,6'],
            'template' => '-ac %s',
            'available_for' => ['aac', 'libfdk_aac', 'libvorbis', 'libopus'],
        ],

        // --- AAC specific ---
        'audio_vbr' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'VBR (AAC native)',
            'options' => ['0', '1', '2', '3', '4', '5'],
            'help' => 'Variable bitrate. Lets the bitrate fluctuate based on audio complexity.',
            'rules' => ['in:0,1,2,3,4,5'],
            'template' => '-q:a %s',
            'available_for' => ['aac'],
        ],
        'audio_profile' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'AAC Profile',
            'options' => ['aac_low', 'aac_he', 'aac_he_v2', 'aac_ld', 'aac_eld'],
            'help' => 'AAC-LC is the most compatible with all players.',
            'rules' => ['in:aac_low,aac_he,aac_he_v2,aac_ld,aac_eld'],
            'template' => '-profile:a %s',
            'available_for' => ['aac', 'libfdk_aac'],
        ],

        // --- FDK-AAC specific ---
        'audio_vbr_fdk' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'VBR (FDK)',
            'options' => ['1', '2', '3', '4', '5'],
            'help' => 'VBR usually provides better quality than CBR at the same file size.',
            'rules' => ['in:1,2,3,4,5'],
            'template' => '-vbr %s',
            'available_for' => ['libfdk_aac'],
        ],
        'cutoff' => [
            'type' => 'audio',
            'input_type' => 'integer',
            'label' => 'Cutoff',
            'min' => 0,
            'max' => 20000,
            'help' => '0 lets the encoder decide. Limits high frequencies.',
            'rules' => ['integer', 'min:0', 'max:20000'],
            'template' => '-cutoff %s',
            'available_for' => ['libfdk_aac'],
        ],
        'afterburner' => [
            'type' => 'audio',
            'input_type' => 'boolean',
            'label' => 'Afterburner',
            'help' => 'Slightly improves quality at the cost of more CPU.',
            'rules' => ['boolean'],
            'template' => '-afterburner %s',
            'available_for' => ['libfdk_aac'],
        ],

        // --- Vorbis specific ---
        'vorbis_quality' => [
            'type' => 'audio',
            'input_type' => 'integer',
            'label' => 'Quality',
            'min' => -1,
            'max' => 10,
            'help' => '-1 = lowest, 10 = highest quality. 5 is a good default (~160kbps).',
            'rules' => ['integer', 'min:-1', 'max:10'],
            'template' => '-q:a %s',
            'available_for' => ['libvorbis'],
        ],

        // --- Opus specific ---
        'opus_vbr' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'VBR Mode',
            'options' => ['on', 'off', 'constrained'],
            'help' => '"on" is recommended for best quality. "constrained" limits peaks.',
            'rules' => ['in:on,off,constrained'],
            'template' => '-vbr %s',
            'available_for' => ['libopus'],
        ],
        'opus_application' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Application',
            'options' => ['audio', 'voip', 'lowdelay'],
            'help' => '"audio" for music/general, "voip" for speech, "lowdelay" for real-time.',
            'rules' => ['in:audio,voip,lowdelay'],
            'template' => '-application %s',
            'available_for' => ['libopus'],
        ],

    ],

    'formats' => [
        'hls' => [
            'label' => 'HLS',
            'description' => 'HTTP Live Streaming. Best for Apple devices and broad compatibility.',
            'protocols' => ['hls'],
            'containers' => ['mp4'],
        ],
        'dash' => [
            'label' => 'DASH',
            'description' => 'Dynamic Adaptive Streaming over HTTP. Supports all codecs and containers.',
            'protocols' => ['dash'],
            'containers' => ['mp4', 'webm'],
        ],
        'mp4' => [
            'label' => 'MP4',
            'description' => 'Progressive download. Single file output.',
            'protocols' => [],
            'containers' => ['mp4'],
        ],
    ],
];
