<?php

return [
    'codecs' => [
        [
            'codec' => 'libx264',
            'type' => 'video',
            'label' => 'H.264 (AVC)',
            'description' => 'High compatibility',
        ],
        [
            'codec' => 'aac',
            'type' => 'audio',
            'label' => 'AAC',
            'description' => 'Standard audio codec with good compatibility',
            'available_for' => ['libx264'],
        ],
        [
            'codec' => 'libfdk_aac',
            'type' => 'audio',
            'label' => 'FDK-AAC',
            'description' => 'The best AAC encoder available.',
            'available_for' => ['libx264'],
        ],
    ],

    'parameters' => [
        // ========== PARÁMETROS DE VIDEO ==========
        'resolution' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Resolution',
            'options' => ['360', '480', '720', '1080'],
            'rules' => ['required', 'in:360,480,720,1080'],
            'template' => '-vf scale=-2:%s',
            'available_for' => ['libx264'],
        ],
        'crf' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'CRF',
            'default' => null,
            'min' => 0,
            'max' => 51,
            'help' => 'Lower is better quality. 23 is the standard.',
            'rules' => ['integer', 'min:0', 'max:51'],
            'template' => '-crf %s',
            'available_for' => ['libx264'],
        ],
        'preset' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Preset',
            'default' => null,
            'options' => ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower', 'veryslow'],
            'rules' => ['in:ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow'],
            'template' => '-preset %s',
            'available_for' => ['libx264'],
        ],
        'video_profile' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Perfil',
            'default' => null,
            'options' => ['baseline', 'main', 'high'],
            'rules' => ['in:baseline,main,high'],
            'template' => '-profile:v %s',
            'available_for' => ['libx264'],
        ],
        'tune' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Tune',
            'default' => null,
            'options' => ['film', 'animation', 'grain', 'stillimage', 'fastdecode', 'zerolatency'],
            'help' => 'Adjust the encoder according to the type of content.',
            'rules' => ['in:film,animation,grain,stillimage,fastdecode,zerolatency'],
            'template' => '-tune %s',
            'available_for' => ['libx264'],
        ],
        'level' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Level',
            'default' => null,
            'options' => ['3.0', '3.1', '4.0', '4.1', '4.2', '5.1', '5.2'],
            'help' => 'Define technical restrictions. 4.1 is the standard for Blu-ray/Web.',
            'rules' => ['in:3.0,3.1,4.0,4.1,4.2,5.1,5.2'],
            'template' => '-level %s',
            'available_for' => ['libx264'],
        ],
        'maxrate' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'Maxrate',
            'default' => null,
            'placeholder' => 'Ej: 5000k',
            'help' => 'Useful for streaming (VBV). Prevents data spikes that cause buffering.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-maxrate %s',
            'available_for' => ['libx264'],
        ],
        'bufsize' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'Bufsize',
            'default' => null,
            'placeholder' => 'Ej: 10000k',
            'help' => 'It is used in conjunction with Maxrate to control the bit rate.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-bufsize %s',
            'available_for' => ['libx264'],
        ],
        'pixel_format' => [
            'type' => 'video',
            'input_type' => 'select',
            'label' => 'Pixel format',
            'default' => 'yuv420p',
            'options' => ['yuv420p', 'yuv422p', 'yuv444p', 'nv12'],
            'help' => 'yuv420p It is the only one compatible with all browsers and devices.',
            'rules' => ['in:yuv420p,yuv422p,yuv444p,nv12'],
            'template' => '-pix_fmt %s',
            'available_for' => ['libx264'],
        ],
        'faststart' => [
            'type' => 'video',
            'input_type' => 'boolean',
            'label' => 'Faststart',
            'default' => true,
            'help' => 'Move the metadata to the beginning so that the video starts playing sooner on the web.',
            'rules' => ['boolean'],
            'template' => '-movflags +faststart',
            'available_for' => ['libx264'],
        ],
        'constant_bitrate' => [
            'type' => 'video',
            'input_type' => 'ktext',
            'label' => 'CBR',
            'default' => null,
            'placeholder' => 'Ej: 2500k',
            'help' => 'If it fills up, it will ignore the CRF to keep this bitrate fixed.',
            'rules' => ['regex:/^\d+k$/i'],
            'template' => '-b:v %s',
            'available_for' => ['libx264'],
        ],
        'gop_size' => [
            'type' => 'video',
            'input_type' => 'integer',
            'label' => 'GOP Size (Keyframes)',
            'default' => null,
            'help' => 'Distancia entre fotogramas clave. Para streaming usar el doble del framerate (ej: 60 para 30fps).',
            'rules' => ['nullable', 'integer', 'min:1'],
            'template' => '-g %s',
            'available_for' => ['libx264'],
        ],

        // ========== PARÁMETROS DE AUDIO ==========
        'audio_codec' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Audio Codec',
            'options' => ['aac', 'libfdk_aac'],
            'rules' => ['required', 'in:aac,libfdk_aac'],
            'template' => '-acodec %s',
            'available_for' => ['libx264'],
        ],
        'audio_bitrate' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Audio Bitrate',
            'default' => '128k',
            'options' => ['64k', '96k', '128k', '160k', '192k', '256k', '320k'],
            'rules' => ['in:64k,96k,128k,160k,192k,256k,320k'],
            'template' => '-b:a %s',
            'available_for' => ['aac', 'libfdk_aac'],
        ],
        'sample_rate' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Sample Rate',
            'default' => '44100',
            'options' => ['22050', '32000', '44100', '48000'],
            'help' => '44100Hz It is the CD standard; 48000Hz is used in professional video.',
            'rules' => ['in:22050,32000,44100,48000'],
            'template' => '-ar %s',
            'available_for' => ['aac', 'libfdk_aac'],
        ],
        'channels' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Channels',
            'default' => '2',
            'options' => ['1', '2', '6'],
            'help' => 'Most web videos use stereo.',
            'rules' => ['in:1,2,6'],
            'template' => '-ac %s',
            'available_for' => ['aac', 'libfdk_aac'],
        ],
        'audio_vbr' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'VBR',
            'default' => null,
            'options' => [
                '0',
                '1',
                '2',
                '3',
                '4',
                '5',
            ],
            'help' => 'Usa -q:a en FFmpeg. It allows the bitrate to go up or down depending on the complexity of the sound.',
            'rules' => ['in:0,1,2,3,4,5'],
            'template' => '-q:a %s',
            'available_for' => ['aac'],
        ],
        'audio_profile' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'Perfil AAC',
            'default' => null,
            'options' => ['aac_low', 'aac_he', 'aac_he_v2', 'aac_ld', 'aac_eld'],
            'help' => 'AAC-LC It is the most compatible with all players.',
            'rules' => ['in:aac_low,aac_he,aac_he_v2,aac_ld,aac_eld'],
            'template' => '-profile:a %s',
            'available_for' => ['aac', 'libfdk_aac'],
        ],
        'audio_vbr_fdk' => [
            'type' => 'audio',
            'input_type' => 'select',
            'label' => 'VBR',
            'default' => null,
            'options' => ['1', '2', '3', '4', '5'],
            'help' => 'VBR It usually provides better sound quality than CBR at the same weight.',
            'rules' => ['in:1,2,3,4,5'],
            'template' => '-vbr %s',
            'available_for' => ['libfdk_aac'],
        ],
        'cutoff' => [
            'type' => 'audio',
            'input_type' => 'integer',
            'label' => 'Cutoff',
            'default' => null,
            'min' => 0,
            'max' => 20000,
            'help' => '0 It allows the encoder to decide. It limits high frequencies.',
            'rules' => ['integer', 'min:0', 'max:20000'],
            'template' => '-cutoff %s',
            'available_for' => ['libfdk_aac'],
        ],
        'afterburner' => [
            'type' => 'audio',
            'input_type' => 'boolean',
            'label' => 'Afterburner',
            'default' => null,
            'help' => 'Slightly improves quality at the cost of a little more CPU.',
            'rules' => ['boolean'],
            'template' => '-afterburner %s',
            'available_for' => ['libfdk_aac'],
        ],
    ]
];
